version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: saleor-postgres
    restart: always
    environment:
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor
      POSTGRES_DB: saleor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: saleor-redis
    restart: always
    ports:
      - "6379:6379"

  saleor-api:
    build:
      context: https://github.com/saleor/saleor.git
      dockerfile: Dockerfile
    container_name: saleor-api
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DEBUG: "False"
      SECRET_KEY: "your-super-secret-key"
      ALLOWED_HOSTS: "*"
      DATABASE_URL: postgres://saleor:saleor@postgres:5432/saleor
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"

  saleor-dashboard:
    image: nginx:alpine
    container_name: saleor-dashboard
    volumes:
      - dashboard_data:/usr/share/nginx/html
    ports:
      - "9000:80"
    depends_on:
      - saleor-api

volumes:
  postgres_data:
  dashboard_data:
