version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: saleor-postgres
    restart: always
    environment:
      POSTGRES_USER: saleor
      POSTGRES_PASSWORD: saleor
      POSTGRES_DB: saleor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: saleor-redis
    restart: always
    ports:
      - "6380:6379" # external 6380, internal 6379

  saleor-api:
    build:
      context: https://github.com/saleor/saleor.git
      dockerfile: Dockerfile
    container_name: saleor-api
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DEBUG: "False"
      SECRET_KEY: "your-super-secret-key" # generate your own secret in production
      ALLOWED_HOSTS: "*"
      ALLOWED_CLIENT_HOSTS: "localhost,185.158.132.8"
      DATABASE_URL: postgres://saleor:saleor@postgres:5432/saleor
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8010:8000" # external 8010, internal 8000

  saleor-dashboard:
    image: nginx:alpine
    container_name: saleor-dashboard
    restart: always
    volumes:
      - /root/dashboard_static:/usr/share/nginx/html
    ports:
      - "9000:80"
    depends_on:
      - saleor-api
    environment:
      API_URI: http://saleor-api:8000/graphql/

volumes:
  postgres_data:
